version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: "always"
    ports:
      - "9090:9000"
    environment:
      - "MINIO_ACCESS_KEY=blog2018"
      - "MINIO_SECRET_KEY=blog2018"
    command: server /data
    volumes:
      - ../data/minio_data:/data
    networks:
      - blog

networks:
  blog:
    external: true
