version: '3'
services:
  #授权服务
  mointor:
    image: registry.cn-shenzhen.aliyuncs.com/blog/monitor:latest
    container_name: monitor
    restart: always
    ports:
      - 8606:8606
    networks:
      - blog
    environment:
      - COMPOSE_PROJECT_NAME=monitor
    volumes:
      - ../log/:/logs/
      - ../config/monitor/:/config/
networks:
  blog:
    external: true
