version: '3'
services:
  #授权服务
  search:
    image: registry.cn-shenzhen.aliyuncs.com/blog/search:latest
    container_name: search
    restart: always
    ports:
      - 8605:8605
    networks:
      - blog
    environment:
      - COMPOSE_PROJECT_NAME=search
    volumes:
      - ../log/:/logs/
networks:
  blog:
    external: true
