name: blog CI/CD/DEV

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: dev
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set SSH Environment
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
        echo "${{ secrets.ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 700 ~/.ssh/*
        ls -l ~/.ssh/
    - name: Download config file and replace
      run: |
        git clone git@github.com:624/prod_configuration.git
        mv -f ./prod_configuration/dev_config/admin/application.yml ./admin/src/main/resources/application.yml
        mv -f ./prod_configuration/dev_config/eureka/application.yml ./eureka/src/main/resources/application.yml
        mv -f ./prod_configuration/dev_config/picture/application.yml ./picture/src/main/resources/application.yml
        mv -f ./prod_configuration/dev_config/sms/application.yml ./sms/src/main/resources/application.yml
        mv -f ./prod_configuration/dev_config/web/application.yml ./web/src/main/resources/application.yml
        mv -f ./prod_configuration/dev_config/search/application.yml ./search/src/main/resources/application.yml
        mv -f ./prod_configuration/dev_config/vue_admin/prod.env.js ./vue_admin/config/prod.env.js
        mv -f ./prod_configuration/dev_config/vue_web/prod.env.js ./vue_web/config/prod.env.js
    - name: Build Java jar
      run: |
        mvn clean install
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build vue_admin and vue_web
      run: |
        cd ./vue_admin
        npm install
        npm run build
        cd ..
        cd ./vue_web
        npm install
        npm run build
        cd ..
    - name: Move files and compress
      run: |
        mkdir -p transfer_files
        mv ./admin/target/admin-0.0.1-SNAPSHOT.jar ./transfer_files/admin-0.0.1-SNAPSHOT.jar
        mv ./sms/target/sms-0.0.1-SNAPSHOT.jar ./transfer_files/sms-0.0.1-SNAPSHOT.jar
        mv ./eureka/target/eureka-0.0.1-SNAPSHOT.jar ./transfer_files/eureka-0.0.1-SNAPSHOT.jar
        mv ./picture/target/picture-0.0.1-SNAPSHOT.jar ./transfer_files/picture-0.0.1-SNAPSHOT.jar
        mv ./web/target/web-0.0.1-SNAPSHOT.jar ./transfer_files/web-0.0.1-SNAPSHOT.jar
        mv ./search/target/search-0.0.1-SNAPSHOT.jar ./transfer_files/search-0.0.1-SNAPSHOT.jar
        mv ./vue_web/dist ./transfer_files/web_dist
        mv ./vue_admin/dist ./transfer_files/admin_dist
        tar -zcvf  transfer_files.tar.gz transfer_files/
    - name: Scp file to aliyun
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        source: "transfer_files.tar.gz"
        target: "/home"
    - name: Distribution and backup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home
          tar -zxvf /home/transfer_files.tar.gz

          echo "################# admin moving #################"

          if [ -f "/home/blog/admin/admin-0.0.1-SNAPSHOT.jar.bak" ];then
            echo "admin.jar.bak exists and is being deleted"
            rm -f /home/blog/admin/admin-0.0.1-SNAPSHOT.jar.bak
          fi
          if [ -f "/home/blog/admin/admin-0.0.1-SNAPSHOT.jar" ];then
            echo "admin.jar exists and is being backup"
            mv /home/blog/admin/admin-0.0.1-SNAPSHOT.jar /home/blog/admin/admin-0.0.1-SNAPSHOT.jar.bak
          fi
          mv /home/transfer_files/admin-0.0.1-SNAPSHOT.jar /home/blog/admin/admin-0.0.1-SNAPSHOT.jar


          echo "################# sms moving #################"

          if [ -f "/home/blog/sms/sms-0.0.1-SNAPSHOT.jar.bak" ];then
            echo "sms.jar.bak exists and is being deleted"
            rm -f /home/blog/sms/sms-0.0.1-SNAPSHOT.jar.bak
          fi
          if [ -f "/home/blog/admin/admin-0.0.1-SNAPSHOT.jar" ];then
            echo "sms.jar exists and is being backup"
            mv /home/blog/sms/sms-0.0.1-SNAPSHOT.jar /home/blog/sms/sms-0.0.1-SNAPSHOT.jar.bak
          fi
          mv /home/transfer_files/sms-0.0.1-SNAPSHOT.jar /home/blog/sms/sms-0.0.1-SNAPSHOT.jar


          echo "################# eureka moving #################"

          if [ -f "/home/blog/eureka/eureka-0.0.1-SNAPSHOT.jar.bak" ];then
            echo "eureka.jar.bak exists and is being deleted"
            rm -f /home/blog/eureka/eureka-0.0.1-SNAPSHOT.jar.bak
          fi
          if [ -f "/home/blog/eureka/eureka-0.0.1-SNAPSHOT.jar" ];then
            echo "eureka.jar exists and is being backup"
            mv /home/blog/eureka/eureka-0.0.1-SNAPSHOT.jar /home/blog/eureka/eureka-0.0.1-SNAPSHOT.jar.bak
          fi
          mv /home/transfer_files/eureka-0.0.1-SNAPSHOT.jar /home/blog/eureka/eureka-0.0.1-SNAPSHOT.jar


          echo "################# picture moving #################"

          if [ -f "/home/blog/picture/picture-0.0.1-SNAPSHOT.jar.bak" ];then
            echo "picture.jar.bak exists and is being deleted"
            rm -f /home/blog/picture/picture-0.0.1-SNAPSHOT.jar.bak
          fi
          if [ -f "/home/blog/picture/picture-0.0.1-SNAPSHOT.jar" ];then
            echo "picture.jar exists and is being backup"
            mv /home/blog/picture/picture-0.0.1-SNAPSHOT.jar /home/blog/picture/picture-0.0.1-SNAPSHOT.jar.bak
          fi
          mv /home/transfer_files/picture-0.0.1-SNAPSHOT.jar /home/blog/picture/picture-0.0.1-SNAPSHOT.jar


          echo "################# web moving #################"

          if [ -f "/home/blog/web/web-0.0.1-SNAPSHOT.jar.bak" ];then
            echo "web.jar.bak exists and is being deleted"
            rm -f /home/blog/web/web-0.0.1-SNAPSHOT.jar.bak
          fi
          if [ -f "/home/blog/web/web-0.0.1-SNAPSHOT.jar" ];then
            echo "web.jar exists and is being backup"
            mv /home/blog/web/web-0.0.1-SNAPSHOT.jar /home/blog/web/web-0.0.1-SNAPSHOT.jar.bak
          fi
          mv /home/transfer_files/web-0.0.1-SNAPSHOT.jar /home/blog/web/web-0.0.1-SNAPSHOT.jar

          echo "################# search moving #################"

          if [ -f "/home/blog/search/search-0.0.1-SNAPSHOT.jar.bak" ];then
            echo "search.jar.bak exists and is being deleted"
            rm -f /home/blog/search/search-0.0.1-SNAPSHOT.jar.bak
          fi
          if [ -f "/home/blog/search/search-0.0.1-SNAPSHOT.jar" ];then
            echo "search.jar exists and is being backup"
            mv /home/blog/search/search-0.0.1-SNAPSHOT.jar /home/blog/search/search-0.0.1-SNAPSHOT.jar.bak
          fi
          mv /home/transfer_files/search-0.0.1-SNAPSHOT.jar /home/blog/search/search-0.0.1-SNAPSHOT.jar


          echo "################# vue_web moving #################"

          if [ -d "/home/blog/vue_web/dist.bak/" ];then
            echo "vue_web dist.bak exists and is being deleted"
            cd /home/blog/vue_web
            rm -rf dist.bak/
          fi
          if [ -d "/home/blog/vue_web/dist/" ];then
            echo "vue_web dist exists and is being backup"
            mv /home/blog/vue_web/dist /home/blog/vue_web/dist.bak
          fi
          mv /home/transfer_files/web_dist /home/blog/vue_web/dist


          echo "################# vue_admin moving #################"

          if [ -d "/home/blog/vue_admin/dist.bak/" ];then
            echo "vue_admin dist.bak exists and is being deleted"
            cd /home/blog/vue_admin
            rm -rf dist.bak/
          fi
          if [ -d "/home/blog/vue_admin/dist/" ];then
            echo "vue_admin dist exists and is being backup"
            mv /home/blog/vue_admin/dist /home/blog/vue_admin/dist.bak
          fi
          mv /home/transfer_files/admin_dist /home/blog/vue_admin/dist

          echo "################# rm transfer_files.tar.gz #################"
          rm -rf /home/transfer_files.tar.gz
          echo "################# rm transfer_files #################"
          rm -rf /home/transfer_files

    - name: Start eureka
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home/blog/eureka/
          ./shutdown.sh
          ./startup.sh
    - name: Start picture
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home/blog/picture/
          ./shutdown.sh
          ./startup.sh
    - name: Start admin
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home/blog/admin/
          ./shutdown.sh
          ./startup.sh
    - name: Start sms
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home/blog/sms/
          ./shutdown.sh
          ./startup.sh
    - name: Start web
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home/blog/web/
          ./shutdown.sh
          ./startup.sh
    - name: Start search
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_IP_DEV }}
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        port: ${{ secrets.DOCKER_PORT }}
        script: |
          cd /home/blog/search/
          ./shutdown.sh
